meta_product_name: "Milyst"
meta_title: "Milyst | The easiest way to create and share your shopping lists"
meta_description: "Easily create and share your shopping lists, quickly add new items to your lists and tap to indicate when you have it it your trolley."
meta_image: "milystfb.jpg" # should exist in `app/assets/images/`
